### ISSUE TITLE
Does HebMorph use Hspell v1.3?

### ISSUE THREAD

**Issue by Trey314159** [synhershko/elasticsearch-analysis-hebrew#32]
Hi! I see that back when users of the plugin had to download the Hspell files separately, the compiled files were based on Hspell v1.2. Is the current version of HebMorph also using Hspell v1.2, or is it up to v1.3? If it is at v1.2, are there any plans to update to v1.3? Thanks!

**Comment by synhershko** [comment]
The ES plugin is using the same binaries as in the HebMorph repo - which as you indicate are based on 1.2. Since we have shifted to a different dictionary we no longer maintain the hspell files, which are only useful for open-source usages. Any closed source usage should be using the commercial version, which is using an entirely different dictionary.
