### ISSUE TITLE
ES 6.4.2 support

### ISSUE THREAD

**Issue by Trey314159** [synhershko/elasticsearch-analysis-hebrew#47]
Is there a timeline for supporting ES 6.x, and specifically ES 6.4.2, in the open source version of the plugin? in issue #40 @synhershko said "We will release the OSS flavor later this year." Is that still the plan? Can we expect it in the next couple of months at the latest?

I know there is a commercial version that supports ES 6.x, but I'm not looking for the commercial version. Our upgrade to ES 6 has been delayed a bit for other reasons, but if there is no version of HebMorph available or even on the horizon when we do upgrade, we may have to pull language-specific support for Hebrew and go back to the default language analyzer, which is not a great outcome.

**Comment by synhershko** [comment]
Hello @Trey314159 ,

As you surely know the term "free software" within the context of AGPL3 refers to the freedom to use, modify and convey the software, and does not mean "free of charge" (see the terms of AGPL3 at: https://github.com/synhershko/elasticsearch-analysis-hebrew/blob/master/agpl-3.0.txt).

Thus, any use of our software is subject to payment. We are willing to exempt users from payment, in specific cases, mostly in noncommercial usage. For the purpose of settling the payment or obtaining an exemption please contact us at info@bigdataboutique.com or myself in private channels.
 
We currently do not have a date for releasing the OSS flavor. Having said that, please note that it also will be subject to a charge as stated above.

Since we have 6.x and specifically 6.4.2 plugin versions released and distributed to our listed users, I will go ahead and close this issue since it's already resolved.
 
We thank you for you interest.
